### ISSUE TITLE
tbox windows下编译android版本遇到的问题

### ISSUE THREAD

**Issue by songqingtian** [tboox/community#17]
checking for the architecture ... armv7-a
checking for the SDK version of NDK ... android-27
checking for the version of toolchains ... 4.9
checking for the posix_getpagesize ... ok
checking for the posix_socket ... ok
checking for the libc_setlocale ... ok
checking for the libc_kill ... ok
checking for the posix_pwritev ... no
checking for the posix_poll ... ok
checking for the libm_atan2 ... ok
checking for the libc_wcsncat ... ok
checking for the polarssl ... no
checking for the posix_execvp ... ok
checking for the posix_fork ... ok
checking for the posix_getifaddrs ... ok
checking for the libc_strcat ... ok
checking for the libc_wcsstr ... ok
checking for the libm_pow ... ok
checking for the libc_memcpy ... ok
checking for the libm_sqrtf ... ok
checking for the libc_wcsnlen ... ok
checking for the libm_acosf ... ok
checking for the libc_strnlen ... ok
checking for the libc_random ... ok
checking for the posix_copyfile ... no
checking for the libm_atanf ... ok
checking for the libc_wcsncpy ... ok
checking for the posix_gethostbyaddr ... ok
checking for the posix_sendfile ... ok
checking for the systemv_semtimedop ... no
checking for the libc_strncmp ... ok
checking for the libc_strncasecmp ... ok
checking for the libc_strlcpy ... ok
checking for the posix_preadv ... no
checking for the posix_stat64 ... ok
checking for the libc_wcscpy ... ok
checking for the libm_tanf ... ok
checking for the libc_strncpy ... ok
checking for the posix_waitpid ... ok
checking for the libc_localtime ... ok
checking for the posix_pread64 ... ok
checking for the posix_sysconf ... ok
checking for the libc_signal ... ok
checking for the libc_strstr ... ok
checking for the libm_log2f ... ok
checking for the libm_fmodf ... ok
checking for the libc_wcstombs ... ok
checking for the posix_regcomp ... ok
checking for the posix_readv ... ok
checking for the wchar ... no
checking for the libm_exp ... ok
checking for the posix_pthread_create ... ok
checking for the libc_setjmp ... ok
checking for the libc_strcasestr ... ok
checking for the posix_posix_spawnp ... no
checking for the libc_mktime ... ok
checking for the libm_acos ... ok
checking for the libc_backtrace ... no
checking for the posix_sched_yield ... ok
checking for the libm_sincosf ... no
checking for the libc_wcscmp ... ok
checking for the posix_fdatasync ... ok
checking for the posix_dlopen ... ok
checking for the posix_regexec ... ok
checking for the posix_vfork ... ok
checking for the libc_mbstowcs ... ok
checking for the posix_writev ... ok
checking for the openssl ... no
checking for the posix_epoll_create ... ok
checking for the systemv_semget ... ok
checking for the zlib ... no
checking for the posix_pthread_key_delete ... ok
checking for the posix_open ... ok
checking for the posix_pthread_key_create ... ok
checking for the libc_gmtime ... ok
checking for the libc_wcscasecmp ... ok
checking for the libm_atan ... ok
checking for the libc_memmove ... ok
checking for the libm_asinf ... ok
checking for the pcre ... no
checking for the libm_sincos ... no
checking for the libc_strcmp ... ok
checking for the libc_strcasecmp ... ok
checking for the posix_pthread_setspecific ... ok
checking for the libc_memset ... ok
checking for the libc_fputs ... ok
checking for the posix_gethostbyname ... ok
checking for the posix_execvpe ... ok
checking for the posix_epoll_wait ... ok
checking for the libc_wcsncasecmp ... ok
checking for the mysql ... no
checking for the libc_strcpy ... ok
checking for the libm_sqrt ... ok
checking for the posix_sem_init ... ok
checking for the libc_wcslen ... ok
checking for the libc_memmem ... ok
checking for the libc_gettimeofday ... ok
checking for the posix_getnameinfo ... ok
checking for the libc_strlen ... ok
checking for the libc_wcslcpy ... ok
checking for the libc_wcscasestr ... no
checking for the libc_wcsncmp ... ok
checking for the libm_log2 ... ok
checking for the libm_cos ... ok
checking for the posix_opendir ... ok
checking for the posix_select ... ok
checking for the libm_sin ... ok
checking for the pcre2 ... no
checking for the libm_tan ... ok
checking for the libc_sigsetjmp ... ok
checking for the libc_memcmp ... ok
checking for the libc_wcscat ... ok
checking for the posix_gethostname ... ok
checking for the mbedtls ... no
checking for the libm_sinf ... ok
checking for the libm_fmod ... ok
checking for the sqlite3 ... no
checking for the posix_pthread_mutex_init ... ok
checking for the libm_asin ... ok
checking for the libm_expf ... ok
checking for the libm_atan2f ... ok
checking for the posix_pwrite64 ... ok
checking for the posix_getaddrinfo ... ok
checking for the libm_cosf ... ok
checking for the libc_strncat ... ok
checking for the posix_pthread_getspecific ... ok
checking for the libc_srandom ... ok
checking for the libm_powf ... ok
checking for the posix_getrlimit ... ok
checking for the posix_getdtablesize ... no

error: src\tbox\platform\linux/poller_epoll.c:91:5: error: implicit declaration of function 'sysconf' [-Werror=implicit-function-declaration]
     if (!maxfds) maxfds = sysconf(_SC_OPEN_MAX);
     ^
src\tbox\platform\linux/poller_epoll.c:91:35: error: '_SC_OPEN_MAX' undeclared (first use in this function)
     if (!maxfds) maxfds = sysconf(_SC_OPEN_MAX);
                                   ^
src\tbox\platform\linux/poller_epoll.c:91:35: note: each undeclared identifier is reported only once for each function it appears in
src\tbox\platform\linux/poller_epoll.c: In function 'tb_poller_exit':
src\tbox\platform\linux/poller_epoll.c:221:5: error: implicit declaration of function 'close' [-Werror=implicit-function-declaration]
     if (poller->epfd > 0) close(poller->epfd);
     ^
cc1.exe: all warnings being treated as errors

请问如何解决，谢谢

**Comment by waruqi** [comment]
你可以手动在 poller_epoll.c 里面加个 #include <unistd.h>，或者下载dev分支版本来编译，这个问题之前已经修复，只是还没有merge到master。。

另外，tbox相关问题，尽量在tbox的issues里面去提，谢谢！

**Comment by waruqi** [comment]
master上我也已经更新了，可以更新下试试。
